# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'version2.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QInputDialog, QFileDialog
from PyQt5.QtGui import QIcon
from pdfUtil import *

import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(643, 345)
        MainWindow.setGeometry(350, 250, 600, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(200, 10, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(48)
        font.setItalic(False)
        self.logoLabel.setFont(font)
        self.logoLabel.setObjectName("logoLabel")
        self.actionsTab = QtWidgets.QTabWidget(self.centralwidget)
        self.actionsTab.setGeometry(QtCore.QRect(0, 80, 641, 161))
        self.actionsTab.setMouseTracking(False)
        self.actionsTab.setMovable(False)
        self.actionsTab.setObjectName("actionsTab")
        self.combineTab = QtWidgets.QWidget()
        self.combineTab.setObjectName("combineTab")
        self.pbCombine = QtWidgets.QPushButton(self.combineTab)
        self.pbCombine.setGeometry(QtCore.QRect(240, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(14)
        self.pbCombine.setFont(font)
        self.pbCombine.setObjectName("pbCombine")
        self.actionsTab.addTab(self.combineTab, "")
        self.removPassTab = QtWidgets.QWidget()
        self.removPassTab.setObjectName("removPassTab")
        self.labelPass = QtWidgets.QLabel(self.removPassTab)
        self.labelPass.setGeometry(QtCore.QRect(200, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(16)
        font.setItalic(False)
        self.labelPass.setFont(font)
        self.labelPass.setObjectName("labelPass")
        self.passBox = QtWidgets.QLineEdit(self.removPassTab)
        self.passBox.setGeometry(QtCore.QRect(300, 20, 113, 25))
        self.passBox.setObjectName("passBox")
        self.pbRemovPass = QtWidgets.QPushButton(self.removPassTab)
        self.pbRemovPass.setGeometry(QtCore.QRect(250, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(14)
        self.pbRemovPass.setFont(font)
        self.pbRemovPass.setObjectName("pbRemovPass")
        self.actionsTab.addTab(self.removPassTab, "")
        self.addPassTab = QtWidgets.QWidget()
        self.addPassTab.setObjectName("addPassTab")
        self.pbAddPass = QtWidgets.QPushButton(self.addPassTab)
        self.pbAddPass.setGeometry(QtCore.QRect(250, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(14)
        self.pbAddPass.setFont(font)
        self.pbAddPass.setObjectName("pbAddPass")
        self.labelAddPass = QtWidgets.QLabel(self.addPassTab)
        self.labelAddPass.setGeometry(QtCore.QRect(200, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(16)
        font.setItalic(False)
        self.labelAddPass.setFont(font)
        self.labelAddPass.setObjectName("labelAddPass")
        self.addPassBox = QtWidgets.QLineEdit(self.addPassTab)
        self.addPassBox.setGeometry(QtCore.QRect(300, 30, 113, 25))
        self.addPassBox.setObjectName("addPassBox")
        self.actionsTab.addTab(self.addPassTab, "")
        self.watermarkTab = QtWidgets.QWidget()
        self.watermarkTab.setObjectName("watermarkTab")
        self.pbSelectWatermark = QtWidgets.QPushButton(self.watermarkTab)
        self.pbSelectWatermark.setGeometry(QtCore.QRect(200, 20, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(18)
        self.pbSelectWatermark.setFont(font)
        self.pbSelectWatermark.setObjectName("pbSelectWatermark")
        self.pbWatermark = QtWidgets.QPushButton(self.watermarkTab)
        self.pbWatermark.setGeometry(QtCore.QRect(250, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(14)
        self.pbWatermark.setFont(font)
        self.pbWatermark.setObjectName("pbWatermark")
        self.actionsTab.addTab(self.watermarkTab, "")
        self.rotateTab = QtWidgets.QWidget()
        self.rotateTab.setObjectName("rotateTab")
        self.radioCK = QtWidgets.QRadioButton(self.rotateTab)
        self.radioCK.setGeometry(QtCore.QRect(250, 20, 96, 23))
        font = QtGui.QFont()
        font.setItalic(False)
        self.radioCK.setFont(font)
        self.radioCK.setObjectName("radioCK")
        self.radioCCK = QtWidgets.QRadioButton(self.rotateTab)
        self.radioCCK.setGeometry(QtCore.QRect(250, 50, 121, 23))
        self.radioCCK.setObjectName("radioCCK")
        self.pbRotate = QtWidgets.QPushButton(self.rotateTab)
        self.pbRotate.setGeometry(QtCore.QRect(250, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(14)
        self.pbRotate.setFont(font)
        self.pbRotate.setObjectName("pbRotate")
        self.actionsTab.addTab(self.rotateTab, "")
        self.splitTab = QtWidgets.QWidget()
        self.splitTab.setObjectName("splitTab")
        self.splitText = QtWidgets.QLabel(self.splitTab)
        self.splitText.setGeometry(QtCore.QRect(160, 30, 191, 17))
        self.splitText.setObjectName("splitText")
        self.lineSplit = QtWidgets.QLineEdit(self.splitTab)
        self.lineSplit.setGeometry(QtCore.QRect(360, 30, 113, 25))
        self.lineSplit.setObjectName("lineSplit")
        self.pbPlit = QtWidgets.QPushButton(self.splitTab)
        self.pbPlit.setGeometry(QtCore.QRect(260, 70, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(14)
        self.pbPlit.setFont(font)
        self.pbPlit.setObjectName("pbPlit")
        self.actionsTab.addTab(self.splitTab, "")
        self.pdfTodocTab = QtWidgets.QWidget()
        self.pdfTodocTab.setObjectName("pdfTodocTab")
        self.pbTxt = QtWidgets.QPushButton(self.pdfTodocTab)
        self.pbTxt.setGeometry(QtCore.QRect(260, 40, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(14)
        self.pbTxt.setFont(font)
        self.pbTxt.setObjectName("pbTxt")
        self.actionsTab.addTab(self.pdfTodocTab, "")
        self.processpb = QtWidgets.QPushButton(self.centralwidget)
        self.processpb.setGeometry(QtCore.QRect(220, 250, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian SemCond Thin")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.processpb.setFont(font)
        self.processpb.setObjectName("processpb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCredits = QtWidgets.QAction(MainWindow)
        self.actionCredits.setObjectName("actionCredits")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionCredits)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.actionsTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF Tool"))
        self.logoLabel.setText(_translate("MainWindow", "PDF Tool"))
        self.pbCombine.setText(_translate("MainWindow", "Add PDF\'s"))
        self.actionsTab.setTabText(self.actionsTab.indexOf(self.combineTab), _translate("MainWindow", "Combine"))
        self.labelPass.setText(_translate("MainWindow", "Password"))
        self.pbRemovPass.setText(_translate("MainWindow", "Add PDF\'s"))
        self.actionsTab.setTabText(self.actionsTab.indexOf(self.removPassTab), _translate("MainWindow", "Remove Password"))
        self.pbAddPass.setText(_translate("MainWindow", "Add PDF\'s"))
        self.labelAddPass.setText(_translate("MainWindow", "Password"))
        self.actionsTab.setTabText(self.actionsTab.indexOf(self.addPassTab), _translate("MainWindow", "Add Password"))
        self.pbSelectWatermark.setText(_translate("MainWindow", "Select Watermark File"))
        self.pbWatermark.setText(_translate("MainWindow", "Add PDF\'s"))
        self.actionsTab.setTabText(self.actionsTab.indexOf(self.watermarkTab), _translate("MainWindow", "Add Watermark"))
        self.radioCK.setText(_translate("MainWindow", "Clockwise"))
        self.radioCCK.setText(_translate("MainWindow", "Conterclockwise"))
        self.pbRotate.setText(_translate("MainWindow", "Add PDF\'s"))
        self.actionsTab.setTabText(self.actionsTab.indexOf(self.rotateTab), _translate("MainWindow", "Rotate"))
        self.splitText.setText(_translate("MainWindow", "Name of the new splitted files"))
        self.pbPlit.setText(_translate("MainWindow", "Add PDF\'s"))
        self.actionsTab.setTabText(self.actionsTab.indexOf(self.splitTab), _translate("MainWindow", "Split"))
        self.pbTxt.setText(_translate("MainWindow", "Add PDF\'s"))
        self.actionsTab.setTabText(self.actionsTab.indexOf(self.pdfTodocTab), _translate("MainWindow", "Get text to doc"))
        self.processpb.setText(_translate("MainWindow", "Process"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit the App"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Esc"))
        self.actionCredits.setText(_translate("MainWindow", "Credits"))


    @property
    def getFile(self):
        fname = QFileDialog.getOpenFileName(filter='PDF files (*.pdf)')
        return fname[0]

    @property
    def getFiles(self):
        fnames = QFileDialog.getOpenFileNames(filter='PDF files (*.pdf)')
        return fnames[0]


    @property
    def mergeAction(self):
        '''Merge PDF's'''
        pass


    @property
    def decryptAction(self):
        '''Remove Pass of PDF's'''
        pass

    @property
    def encryptAction(self):
        '''Add password to PDF's'''
        pass


    @property
    def rotateAction(self):
        '''Rotate CW or CCW'''
        pass


    @property
    def watermarkAction(self):
        '''Add watermark'''
        pass


    @property
    def splitAction(self):
        '''Split pdf by 1 page'''
        pass


    @property
    def gettextAction(self):
        pass

    

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())